version: '3.9'

services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: viet_autoescuela
      TZ: Asia/Ho_Chi_Minh
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./infra/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
